### ISSUE TITLE
Conseils de caillou

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [Hama99o/my-cv#33]
# Improve dark mode management

Dans le fichier de store: Make generic methods, and put your data in a hash, instead of repeating your conditions

```js
hasNightMood = false

lightDarkClasses = {
  textColor: { dark: '..', light: '..' },
  linkColor: { dark: '...', light: '..' }
}

getTheme() {
  hasNightMood ? 'dark' : 'light'
}

getClass(attribute) {
  lightDarkClasses[attribute][theme]
}
```

# Further improvement of dark mode management
Dark/light mode should change one class only, on the `<body>` in `App.vue`
Then in the css, we do this :

```css
body.dark {
  color: white;
  
  a {
     color: blue;
  }
}

body.light {
  color: black;
  
  a {
     color: lightblue;
  }
}
```

# Links in dark mode
Add a lighter blue for links in dark mode

# Responsiveness

Reduce the margins on the side of the console in small screens

# Content

In your experiences, make the experience in Jam taller by adding more text in it (the text from your CV)

In your experiences, add another link to your CV.
In contact, add a link to your linkedin
In profile, add a link to your github

These links can just be a logo of linkedin or github, no need to write text i think.
